const express = require('express');
const farmerrouter = express.Router();
const farmerController = require('../controllers/farmerController');
farmerrouter.post('/api/add-crop',farmerController.PostAddCrop);
farmerrouter.get('/api/listed-crops',farmerController.getMyListedCrops);
farmerrouter.get('/api/requested-crops',farmerController.getRequestedCrops);
farmerrouter.patch('/api/accept/:requestId',farmerController.acceptCropRequest);
farmerrouter.patch('/api/reject/:requestId',farmerController.rejectCropRequest);
farmerrouter.get('/api/farmer/profile',farmerController.getProfile);
farmerrouter.patch('/api/requests/accept/:requestId',farmerController.acceptFirmRequest);
module.exports = farmerrouter;
